### PR TITLE
Added wp7 support.

### PR DESCRIPTION
**Pull request by ghost**
Tested on Lumia 800.

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Wow wow easier :) 

It will be enough to just write in README.md something like "if you want to user JetImageLoader in wp7 project you need to reference Microsoft.Bcl library to provide support for async/await instructions. "

You can add dependency on that lib via NuGet: PM> Install-Package Microsoft.Bcl

Attaching executable files in repository is very bad practice, files like NuGet.exe should never be part of project sources :) Project should contain just sources. 

Also, I don't think, that we need to create JetImageLoaderWp7 folder for that purposes, because source code wouldn't be changed for wp7, referencing Microsoft.Bcl is enough for that

**Comment by artem-zinnatullin** [comment]
I just wanted to give you little task with updating `README.md` about using `JetImageLoader` in wp7 projects and you will became project contributor :)

**Comment by ghost** [comment]
Hm.. what would be the easiest way to keep wp7 version easy-to-build? 
I though, having separate project and linking new files would be pretty ok.

Actually, i can do that: sample is a bit outdated :)

**Comment by artem-zinnatullin** [comment]
Easiest way would be: install `Microsoft.Bcl` from `NuGet` and use `JetImageLoader` in wp7 project :)

**Comment by ghost** [comment]
There's no possibility to downgrade Wp8 project (or library) to Wp7, and Wp8 library would not work with Wp7 project, so only adding Bcl to project would not help.
So, i created new wp7 library, linked your files, added Bcl, and so on.. it took dozen of minutes - maybe there can be easier way?)

**Comment by artem-zinnatullin** [comment]
Oh, you are right. I forgot that new project required for that. Hmm.. May be we need structure like: `JetImageLoaderCore`, `JetImageLoaderWP8`, `JetImageLoaderWP7`, `JetImageLoaderWindowsStore`

**Comment by ghost** [comment]
Hm.. but what would be in Core and in Wp8? 

Well... probably, something like:
- Core with all stuff, 
- WP8 with only Core (just a wrapper), 
- WP7 with Core and Bcl
- WS with Core and WhateverWouldBeNeeded

**Comment by ghost** [comment]
Pushed fixed LimitedStorageCache for wp7.

**Comment by ghost** [comment]
And why it is pushed with my another account? In a GitHub app i'm registered as current user.

**Comment by artem-zinnatullin** [comment]
This pull request will be changed with another one, closing

**Pull request closed without merging**
