### PR TITLE
Adding Windows Phone 7 Project

### PR DESCRIPTION
**Pull request by rahulpnath**
Added a Windows Phone 7 project and linked files from phone 8 project for fix #17 and #27
Added packages.config for Microsoft.Bcl.Async.
Nuget Package Restore should be enabled to restore the referred
packages.
https://docs.nuget.org/docs/reference/package-restore

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Hello, @rahulpnath, I'll check your pull request in next few days and if everything will be okay, I'll merge it, thank you :)

**Comment by rahulpnath** [comment]
Cool thanks!

Rahul
http://rahulpnath.com

**Comment by rahulpnath** [comment]
Got a chance to look into this?

**Comment by artem-zinnatullin** [comment]
Sorry, I'll do it in 1-2 days, too much things to do..

---

Best regards, Artem Zinnatullin

**Comment by rahulpnath** [comment]
Sure. I was just checking ☺. It is an awesome library/project.

Rahul
http://rahulpnath.com

**Pull request merged**
